version: '3.1'

services:
  mongo:
    container_name: mongo-container-js-expert
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: docker
    ports:
      - '25015:27017'
